module.exports = {
  apps: [
    {
      name: 'auth-service',
      cwd: './services/auth-service',
      script: 'index.js',
      env: { 
        PORT: 3006, 
        NODE_ENV: 'production',
        AUTH_SERVICE_URL: 'http://localhost:3006',
        RIPPLIFY_SERVICE_URL: 'http://localhost:3007',
        SHOPALIZE_SERVICE_URL: 'http://localhost:3008',
        WATCHTOWER_SERVICE_URL: 'http://localhost:3009',
        ADMIN_SERVICE_URL: 'http://localhost:3010',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'ripplify-service',
      cwd: './services/ripplify-service',
      script: 'index.js',
      env: { 
        RIPPLIFY_PORT: 3007, 
        NODE_ENV: 'production',
        AUTH_SERVICE_URL: 'http://localhost:3006',
        RIPPLIFY_SERVICE_URL: 'http://localhost:3007',
        SHOPALIZE_SERVICE_URL: 'http://localhost:3008',
        WATCHTOWER_SERVICE_URL: 'http://localhost:3009',
        ADMIN_SERVICE_URL: 'http://localhost:3010',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'shopalize-service',
      cwd: './services/shopalize-service',
      script: 'index.js',
      env: { 
        SHOPALIZE_PORT: 3008, 
        NODE_ENV: 'production',
        AUTH_SERVICE_URL: 'http://localhost:3006',
        RIPPLIFY_SERVICE_URL: 'http://localhost:3007',
        SHOPALIZE_SERVICE_URL: 'http://localhost:3008',
        WATCHTOWER_SERVICE_URL: 'http://localhost:3009',
        ADMIN_SERVICE_URL: 'http://localhost:3010',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'watchtower-service',
      cwd: './services/watchtower-service',
      script: 'index.js',
      env: { 
        WATCHTOWER_PORT: 3009, 
        NODE_ENV: 'production',
        AUTH_SERVICE_URL: 'http://localhost:3006',
        RIPPLIFY_SERVICE_URL: 'http://localhost:3007',
        SHOPALIZE_SERVICE_URL: 'http://localhost:3008',
        WATCHTOWER_SERVICE_URL: 'http://localhost:3009',
        ADMIN_SERVICE_URL: 'http://localhost:3010',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'admin-service',
      cwd: './services/admin-service',
      script: 'index.js',
      env: { 
        ADMIN_PORT: 3010, 
        NODE_ENV: 'production',
        AUTH_SERVICE_URL: 'http://localhost:3006',
        RIPPLIFY_SERVICE_URL: 'http://localhost:3007',
        SHOPALIZE_SERVICE_URL: 'http://localhost:3008',
        WATCHTOWER_SERVICE_URL: 'http://localhost:3009',
        ADMIN_SERVICE_URL: 'http://localhost:3010',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
