module.exports = {
  apps: [
    {
      name: 'auth-service',
      cwd: './services/auth-service',
      script: 'index.js',
      env: { PORT: 3001, NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'ripplify-service',
      cwd: './services/ripplify-service',
      script: 'index.js',
      env: { PORT: 3002, NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'shopalize-service',
      cwd: './services/shopalize-service',
      script: 'index.js',
      env: { PORT: 3003, NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'watchtower-service',
      cwd: './services/watchtower-service',
      script: 'index.js',
      env: { PORT: 3004, NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'admin-service',
      cwd: './services/admin-service',
      script: 'index.js',
      env: { PORT: 3005, NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
