import { useEffect, useState, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useStore } from '@/store'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import LoginModal from '@/components/LoginModal'
import StorePreview from '@/components/StorePreview'
import {
  ShoppingCart, ArrowLeft, Eye, Download, GripVertical, Trash2,
  Palette, Package, FileText, ChevronDown, ChevronUp, Plus, Monitor, Tablet, Smartphone
} from 'lucide-react'
import type { StoreSection, Product, StorePage, Project } from '@/types'

export default function EditorPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const navigate = useNavigate();
  const { currentProject, loadProject, updateProjectTheme, updateProjectPages, updateProjectProducts, updateProjectName } = useStore();
  const [showLogin, setShowLogin] = useState(false);
  const [activeTab, setActiveTab] = useState('sections');
  const [selectedSectionId, setSelectedSectionId] = useState<string | null>(null);
  const [previewMode, setPreviewMode] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');

  useEffect(() => {
    if (projectId) loadProject(projectId);
  }, [projectId, loadProject]);

  useEffect(() => {
    if (!currentProject && projectId) navigate('/');
  }, [currentProject, projectId, navigate]);

  const currentPage = currentProject?.pages[0];

  const handleAddSection = useCallback((type: StoreSection['type']) => {
    if (!currentProject || !currentPage) return;
    const newSection: StoreSection = { id: `section-${Date.now()}`, type, props: getDefaultProps(type) };
    updateProjectPages([{ ...currentPage, sections: [...currentPage.sections, newSection] }]);
  }, [currentProject, currentPage, updateProjectPages]);

  const handleRemoveSection = useCallback((sectionId: string) => {
    if (!currentProject || !currentPage) return;
    updateProjectPages([{ ...currentPage, sections: currentPage.sections.filter(s => s.id !== sectionId) }]);
    if (selectedSectionId === sectionId) setSelectedSectionId(null);
  }, [currentProject, currentPage, selectedSectionId, updateProjectPages]);

  const handleMoveSection = useCallback((index: number, direction: 'up' | 'down') => {
    if (!currentPage) return;
    const sections = [...currentPage.sections];
    const target = direction === 'up' ? index - 1 : index + 1;
    if (target < 0 || target >= sections.length) return;
    [sections[index], sections[target]] = [sections[target], sections[index]];
    updateProjectPages([{ ...currentPage, sections }]);
  }, [currentPage, updateProjectPages]);

  const handleUpdateSectionProps = useCallback((sectionId: string, props: Record<string, unknown>) => {
    if (!currentPage) return;
    updateProjectPages([{
      ...currentPage,
      sections: currentPage.sections.map(s => s.id === sectionId ? { ...s, props: { ...s.props, ...props } } : s),
    }]);
  }, [currentPage, updateProjectPages]);

  const handleAddProduct = useCallback(() => {
    if (!currentProject) return;
    updateProjectProducts([...currentProject.products, {
      id: `product-${Date.now()}`, name: 'New Product', price: 9.99,
      description: 'Product description', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400', category: 'General',
    }]);
  }, [currentProject, updateProjectProducts]);

  const handleUpdateProduct = useCallback((id: string, updates: Partial<Product>) => {
    if (!currentProject) return;
    updateProjectProducts(currentProject.products.map(p => p.id === id ? { ...p, ...updates } : p));
  }, [currentProject, updateProjectProducts]);

  const handleDeleteProduct = useCallback((id: string) => {
    if (!currentProject) return;
    updateProjectProducts(currentProject.products.filter(p => p.id !== id));
  }, [currentProject, updateProjectProducts]);

  const handleExport = useCallback(async () => {
    if (!currentProject) return;
    const JSZip = (await import('jszip')).default;
    const zip = new JSZip();
    zip.file('index.html', generateExportHTML(currentProject));
    zip.file('README.md', `# ${currentProject.name}\n\nGenerated by Shopalize`);
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentProject.name.replace(/\s+/g, '-').toLowerCase()}.zip`;
    a.click();
    URL.revokeObjectURL(url);
  }, [currentProject]);

  if (!currentProject) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0A0E21]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#8A61E0]" />
      </div>
    );
  }

  const sectionTypes: StoreSection['type'][] = ['header', 'hero', 'products', 'features', 'testimonials', 'gallery', 'cta', 'newsletter', 'faq', 'footer'];

  return (
    <div className="min-h-screen flex flex-col bg-[#0A0E21] text-white">
      {/* Top toolbar - light lavender like reference */}
      <nav className="sticky top-0 z-50 border-b border-white/[0.06] bg-[#D5B9E0]">
        <div className="flex items-center justify-between px-4 py-2.5">
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/dashboard')} className="p-1.5 rounded-lg hover:bg-black/10 text-[#1a1147] transition-colors">
              <ArrowLeft className="w-4 h-4" />
            </button>
            <div className="flex items-center gap-2">
              <div className="w-6 h-6 rounded bg-[#8A61E0] flex items-center justify-center">
                <ShoppingCart className="w-3.5 h-3.5 text-white" />
              </div>
              <input
                value={currentProject.name}
                onChange={(e) => updateProjectName(e.target.value)}
                className="h-7 w-40 text-sm font-semibold bg-transparent border-none outline-none text-[#1a1147] placeholder:text-[#1a1147]/40"
              />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="hidden sm:flex items-center bg-[#1a1147]/10 rounded-lg p-0.5 mr-2">
              {([
                { mode: 'desktop' as const, icon: Monitor },
                { mode: 'tablet' as const, icon: Tablet },
                { mode: 'mobile' as const, icon: Smartphone },
              ]).map(({ mode, icon: Icon }) => (
                <button
                  key={mode}
                  className={`p-1.5 rounded-md transition-colors ${previewMode === mode ? 'bg-white text-[#1a1147] shadow-sm' : 'text-[#1a1147]/50 hover:text-[#1a1147]'}`}
                  onClick={() => setPreviewMode(mode)}
                >
                  <Icon className="w-4 h-4" />
                </button>
              ))}
            </div>
            <button
              onClick={() => navigate(`/preview/${currentProject.id}`)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm text-[#1a1147] hover:bg-black/10 transition-colors"
            >
              <Eye className="w-4 h-4" /> Preview
            </button>
            <button
              onClick={handleExport}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm bg-[#8A61E0] text-white hover:bg-[#7B52D1] transition-colors"
            >
              <Download className="w-4 h-4" /> Export
            </button>
          </div>
        </div>
      </nav>

      {/* Main editor area - dark like reference */}
      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        {/* Left sidebar */}
        <aside className="w-full lg:w-80 xl:w-96 border-b lg:border-b-0 lg:border-r border-white/[0.06] bg-[#0F0F2F] overflow-y-auto flex-shrink-0 max-h-[40vh] lg:max-h-none">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="w-full grid grid-cols-3 rounded-none bg-[#0A0E21] h-11 border-b border-white/[0.06]">
              <TabsTrigger value="sections" className="text-xs data-[state=active]:bg-[#8A61E0]/20 data-[state=active]:text-[#B99AE6] text-gray-500">
                <FileText className="w-3.5 h-3.5 mr-1" /> Sections
              </TabsTrigger>
              <TabsTrigger value="products" className="text-xs data-[state=active]:bg-[#8A61E0]/20 data-[state=active]:text-[#B99AE6] text-gray-500">
                <Package className="w-3.5 h-3.5 mr-1" /> Products
              </TabsTrigger>
              <TabsTrigger value="theme" className="text-xs data-[state=active]:bg-[#8A61E0]/20 data-[state=active]:text-[#B99AE6] text-gray-500">
                <Palette className="w-3.5 h-3.5 mr-1" /> Theme
              </TabsTrigger>
            </TabsList>

            <TabsContent value="sections" className="p-3 space-y-3 mt-0">
              <h3 className="text-sm font-semibold text-gray-300">Page Sections</h3>
              <div className="grid grid-cols-5 gap-1.5">
                {sectionTypes.map(type => (
                  <button
                    key={type}
                    onClick={() => handleAddSection(type)}
                    className="flex items-center gap-0.5 px-2 py-1.5 rounded-lg text-[11px] border border-white/[0.06] bg-[#0A0E21] text-gray-400 hover:border-[#8A61E0]/30 hover:text-white transition-colors"
                  >
                    <Plus className="w-2.5 h-2.5" /> {type.charAt(0).toUpperCase() + type.slice(1, 4)}
                  </button>
                ))}
              </div>
              <div className="space-y-1.5">
                {currentPage?.sections.map((section, index) => (
                  <div
                    key={section.id}
                    className={`flex items-center gap-2 p-2.5 rounded-lg border cursor-pointer transition-colors ${
                      selectedSectionId === section.id
                        ? 'bg-[#8A61E0]/15 border-[#8A61E0]/40'
                        : 'bg-[#0A0E21] border-white/[0.06] hover:border-white/[0.12]'
                    }`}
                    onClick={() => setSelectedSectionId(section.id)}
                  >
                    <GripVertical className="w-4 h-4 text-gray-600 flex-shrink-0" />
                    <span className="text-xs font-medium text-gray-300 capitalize">{section.type}</span>
                    <span className="text-[10px] text-gray-600">#{index + 1}</span>
                    <div className="flex gap-0.5 ml-auto">
                      <button className="p-1 rounded hover:bg-white/5 text-gray-500 disabled:opacity-30" onClick={(e) => { e.stopPropagation(); handleMoveSection(index, 'up'); }} disabled={index === 0}>
                        <ChevronUp className="w-3 h-3" />
                      </button>
                      <button className="p-1 rounded hover:bg-white/5 text-gray-500 disabled:opacity-30" onClick={(e) => { e.stopPropagation(); handleMoveSection(index, 'down'); }} disabled={index === currentPage.sections.length - 1}>
                        <ChevronDown className="w-3 h-3" />
                      </button>
                      <button className="p-1 rounded hover:bg-red-500/10 text-red-400" onClick={(e) => { e.stopPropagation(); handleRemoveSection(section.id); }}>
                        <Trash2 className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {selectedSectionId && currentPage && (() => {
                const section = currentPage.sections.find(s => s.id === selectedSectionId);
                if (!section) return null;
                return (
                  <div className="mt-3 rounded-xl border border-white/[0.06] bg-[#0A0E21] p-4">
                    <h4 className="text-sm font-semibold text-white mb-3 capitalize">Edit {section.type}</h4>
                    <div className="space-y-3">
                      {Object.entries(section.props).map(([key, value]) => (
                        <div key={key}>
                          <label className="text-xs text-gray-400 capitalize block mb-1">{key.replace(/([A-Z])/g, ' $1').trim()}</label>
                          {typeof value === 'string' && (
                            <input
                              value={value}
                              onChange={(e) => handleUpdateSectionProps(section.id, { [key]: e.target.value })}
                              className="w-full h-8 px-3 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                            />
                          )}
                          {typeof value === 'number' && (
                            <input
                              type="number"
                              value={value}
                              onChange={(e) => handleUpdateSectionProps(section.id, { [key]: Number(e.target.value) })}
                              className="w-full h-8 px-3 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                            />
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })()}
            </TabsContent>

            <TabsContent value="products" className="p-3 space-y-3 mt-0">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-gray-300">Products ({currentProject.products.length})</h3>
                <button onClick={handleAddProduct} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs bg-[#8A61E0] text-white hover:bg-[#7B52D1] transition-colors">
                  <Plus className="w-3 h-3" /> Add
                </button>
              </div>
              <div className="space-y-2">
                {currentProject.products.map(product => (
                  <div key={product.id} className="p-3 rounded-xl border border-white/[0.06] bg-[#0A0E21]">
                    <div className="flex gap-3">
                      <img src={product.image} alt={product.name} className="w-12 h-12 rounded-lg object-cover flex-shrink-0" />
                      <div className="flex-1 min-w-0 space-y-1.5">
                        <input
                          value={product.name}
                          onChange={(e) => handleUpdateProduct(product.id, { name: e.target.value })}
                          className="w-full h-7 px-2.5 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                          placeholder="Product name"
                        />
                        <div className="flex gap-2">
                          <input
                            type="number"
                            value={product.price}
                            onChange={(e) => handleUpdateProduct(product.id, { price: Number(e.target.value) })}
                            className="w-24 h-7 px-2.5 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                          />
                          <input
                            value={product.category}
                            onChange={(e) => handleUpdateProduct(product.id, { category: e.target.value })}
                            className="flex-1 h-7 px-2.5 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                          />
                        </div>
                        <input
                          value={product.image}
                          onChange={(e) => handleUpdateProduct(product.id, { image: e.target.value })}
                          className="w-full h-7 px-2.5 text-xs rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                        />
                      </div>
                      <button onClick={() => handleDeleteProduct(product.id)} className="self-start p-1 rounded hover:bg-red-500/10 text-red-400">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </TabsContent>

            <TabsContent value="theme" className="p-3 space-y-4 mt-0">
              <h3 className="text-sm font-semibold text-gray-300">Theme Settings</h3>
              <div className="space-y-3">
                {[
                  { key: 'primaryColor', label: 'Primary Color' },
                  { key: 'secondaryColor', label: 'Secondary Color' },
                  { key: 'accentColor', label: 'Accent Color' },
                  { key: 'backgroundColor', label: 'Background Color' },
                  { key: 'textColor', label: 'Text Color' },
                ].map(({ key, label }) => (
                  <div key={key} className="flex items-center gap-3">
                    <input
                      type="color"
                      value={currentProject.theme[key as keyof typeof currentProject.theme] as string}
                      onChange={(e) => updateProjectTheme({ [key]: e.target.value })}
                      className="w-10 h-8 rounded-lg border border-white/[0.06] cursor-pointer bg-transparent"
                    />
                    <div className="flex-1">
                      <label className="text-xs text-gray-400 block mb-1">{label}</label>
                      <input
                        value={currentProject.theme[key as keyof typeof currentProject.theme] as string}
                        onChange={(e) => updateProjectTheme({ [key]: e.target.value })}
                        className="w-full h-7 px-2.5 text-xs rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none focus:border-[#8A61E0]/40"
                      />
                    </div>
                  </div>
                ))}
                <div>
                  <label className="text-xs text-gray-400 block mb-1">Font Family</label>
                  <select
                    value={currentProject.theme.fontFamily}
                    onChange={(e) => updateProjectTheme({ fontFamily: e.target.value })}
                    className="w-full h-8 px-2.5 text-sm rounded-lg border border-white/[0.06] bg-[#0F0F2F] text-white outline-none"
                  >
                    {['Inter', 'Roboto', 'Poppins', 'Playfair Display', 'Montserrat', 'Open Sans', 'Lato', 'Nunito'].map(f => (
                      <option key={f} value={f}>{f}</option>
                    ))}
                  </select>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </aside>

        {/* Preview area */}
        <main className="flex-1 overflow-auto bg-[#0A0E21] p-4 md:p-6">
          <div className={`mx-auto bg-white/[0.02] border border-white/[0.06] rounded-xl overflow-hidden transition-all duration-300 ${
            previewMode === 'desktop' ? 'max-w-full' : previewMode === 'tablet' ? 'max-w-[768px]' : 'max-w-[375px]'
          }`}>
            <StorePreview project={currentProject} />
          </div>
        </main>
      </div>

      <LoginModal open={showLogin} onOpenChange={setShowLogin} />
    </div>
  );
}

function getDefaultProps(type: StoreSection['type']): Record<string, unknown> {
  const defaults: Record<string, Record<string, unknown>> = {
    header: { storeName: 'My Store' },
    hero: { title: 'Welcome', subtitle: 'Discover amazing products', cta: 'Shop Now' },
    products: { title: 'Our Products', columns: 3 },
    features: { title: 'Why Choose Us' },
    testimonials: { title: 'What Our Customers Say' },
    gallery: { title: 'Gallery' },
    cta: { title: 'Get Started Today', text: 'Join thousands of happy customers', cta: 'Sign Up' },
    newsletter: { title: 'Stay Updated', subtitle: 'Subscribe to our newsletter' },
    faq: { title: 'Frequently Asked Questions' },
    footer: { text: '© 2024 My Store' },
  };
  return defaults[type] || {};
}

function generateExportHTML(project: Project): string {
  const theme = project.theme;
  const pages = project.pages;
  const products = project.products;
  const sections: StoreSection[] = pages[0]?.sections || [];

  const sectionHTML = sections.map((s: StoreSection) => {
    switch (s.type) {
      case 'header':
        return `<header style="padding:1rem 2rem;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;justify-content:space-between"><strong style="font-size:1.25rem">${s.props.storeName || 'Store'}</strong><nav><a href="#" style="margin-left:1rem;color:${theme.primaryColor}">Shop</a></nav></header>`;
      case 'hero':
        return `<section style="text-align:center;padding:4rem 2rem;background:linear-gradient(135deg,${theme.primaryColor}11,${theme.secondaryColor}11)"><h1 style="font-size:2.5rem;margin-bottom:1rem;color:${theme.textColor}">${s.props.title}</h1><p style="font-size:1.125rem;color:${theme.textColor}88;margin-bottom:2rem">${s.props.subtitle}</p><a href="#products" style="background:${theme.primaryColor};color:#fff;padding:0.75rem 2rem;border-radius:0.5rem;text-decoration:none;display:inline-block">${s.props.cta}</a></section>`;
      case 'products':
        return `<section id="products" style="padding:3rem 2rem"><h2 style="text-align:center;font-size:1.75rem;margin-bottom:2rem">${s.props.title}</h2><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:1.5rem">${products.map((p: Product) => `<div style="border:1px solid #e5e7eb;border-radius:0.75rem;overflow:hidden"><img src="${p.image}" alt="${p.name}" style="width:100%;height:200px;object-fit:cover"/><div style="padding:1rem"><h3>${p.name}</h3><p style="color:${theme.primaryColor};font-weight:600">$${p.price.toFixed(2)}</p><p style="color:#6b7280;font-size:0.875rem">${p.description}</p></div></div>`).join('')}</div></section>`;
      case 'footer':
        return `<footer style="padding:2rem;text-align:center;border-top:1px solid #e5e7eb;color:#6b7280">${s.props.text || '© 2024'}</footer>`;
      default:
        return `<section style="padding:3rem 2rem;text-align:center"><h2 style="font-size:1.5rem;margin-bottom:1rem">${s.props.title || s.type}</h2></section>`;
    }
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.name}</title>
  <link href="https://fonts.googleapis.com/css2?family=${theme.fontFamily || 'Inter'}:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: '${theme.fontFamily || 'Inter'}', sans-serif; color: ${theme.textColor}; background: ${theme.backgroundColor}; }
    img { max-width: 100%; }
  </style>
</head>
<body>
${sectionHTML}
</body>
</html>`;
}
